"""
Source Schema Analysis Schema.
Defines the output of the Schema Analyst Agent.
"""

from typing import List, Optional, Dict, Any, Literal
from pydantic import BaseModel, Field


class ColumnAnalysis(BaseModel):
    """Analysis results for a single column."""
    column_name: str = Field(description="Original column name")
    column_index: int = Field(description="0-indexed column position")
    
    # Data type analysis
    inferred_type: Literal["string", "integer", "float", "date", "boolean", "mixed", "empty"] = Field(
        default="string",
        description="Inferred data type"
    )
    
    # Semantic type (what the data represents)
    semantic_type: Optional[str] = Field(
        default=None,
        description="Semantic meaning, e.g., 'phone', 'email', 'name', 'address', 'gstin'"
    )
    
    # Statistics
    total_values: int = 0
    null_count: int = 0
    unique_count: int = 0
    
    # Quality indicators
    completeness: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Percentage of non-null values"
    )
    
    # Sample values for AI analysis
    sample_values: List[str] = Field(
        default_factory=list,
        description="Sample of actual values from this column"
    )
    
    # Issues detected
    issues: List[str] = Field(
        default_factory=list,
        description="List of detected issues, e.g., 'mixed formats', 'merged cells'"
    )
    
    # Pattern detection
    detected_pattern: Optional[str] = Field(
        default=None,
        description="Detected regex pattern if applicable"
    )
    
    # Suggested transformations
    suggested_functions: List[str] = Field(
        default_factory=list,
        description="Suggested transformation functions from the registry"
    )


class StructuralIssue(BaseModel):
    """A structural issue with the source file."""
    issue_type: Literal[
        "merged_cells",
        "multi_row_header",
        "empty_rows",
        "empty_columns",
        "inconsistent_types",
        "special_characters",
        "encoding_issues"
    ]
    description: str
    location: Optional[str] = None  # e.g., "Row 5-7", "Column C"
    severity: Literal["critical", "warning", "info"] = "warning"


class SourceSchemaAnalysis(BaseModel):
    """
    Complete analysis of a source file's schema.
    Generated by the Schema Analyst Agent.
    """
    file_name: str = Field(description="Name of the analyzed file")
    sheet_name: Optional[str] = Field(default=None, description="Sheet name if Excel")
    
    # Basic stats
    total_rows: int = 0
    total_columns: int = 0
    sample_rows_analyzed: int = Field(
        default=50,
        description="Number of rows used for analysis"
    )
    
    # Column-level analysis
    columns: List[ColumnAnalysis] = Field(
        default_factory=list,
        description="Analysis for each column"
    )
    
    # Structural issues
    structural_issues: List[StructuralIssue] = Field(
        default_factory=list,
        description="File structure problems detected"
    )
    
    # File encoding
    encoding: Optional[str] = Field(
        default=None,
        description="Detected file encoding"
    )
    
    # Header detection
    header_row: int = Field(
        default=0,
        description="0-indexed row containing headers"
    )
    has_valid_headers: bool = Field(
        default=True,
        description="Whether the file has valid column headers"
    )
    
    # Overall quality
    overall_quality: Literal["good", "fair", "poor"] = Field(
        default="fair",
        description="Overall data quality assessment"
    )
    
    # Recommendations
    preprocessing_steps: List[str] = Field(
        default_factory=list,
        description="Recommended preprocessing steps before transformation"
    )
    
    def get_column_by_name(self, name: str) -> Optional[ColumnAnalysis]:
        """Find a column analysis by name."""
        for col in self.columns:
            if col.column_name.lower() == name.lower():
                return col
        return None
    
    def get_columns_by_semantic_type(self, semantic_type: str) -> List[ColumnAnalysis]:
        """Find all columns with a specific semantic type."""
        return [c for c in self.columns if c.semantic_type == semantic_type]
