"""
Transformation Plan Schema.
Defines the JSON protocol for transformation plans generated by the Planner Agent.
"""

from typing import List, Dict, Any, Optional, Literal
from pydantic import BaseModel, Field
from uuid import uuid4


class TransformationParams(BaseModel):
    """Parameters for a transformation function."""
    # Common parameters - all optional as they vary by function
    delimiter: Optional[str] = None
    culture: Optional[str] = None
    handle_single_name: Optional[str] = None
    pattern: Optional[str] = None
    group_index: Optional[int] = None
    ambiguity_preference: Optional[Literal["US", "UK", "ISO"]] = None
    target_format: Optional[str] = None
    currency_symbol: Optional[str] = None
    mapping_dict: Optional[Dict[str, str]] = None
    default: Optional[str] = None
    fallback_col: Optional[str] = None
    region: Optional[str] = None
    format: Optional[str] = None
    provider: Optional[str] = None
    cache_ttl: Optional[int] = None
    prompt_template: Optional[str] = None
    
    class Config:
        extra = "allow"  # Allow additional parameters


class Transformation(BaseModel):
    """A single transformation step."""
    id: str = Field(description="Unique identifier for this transformation, e.g., 'tf_01'")
    function: str = Field(description="Name of the function from the registry")
    input_col: Optional[str] = Field(default=None, description="Input column name")
    input_cols: Optional[List[str]] = Field(default=None, description="Multiple input columns")
    output_col: Optional[str] = Field(default=None, description="Output column name")
    output_cols: Optional[List[str]] = Field(default=None, description="Multiple output columns")
    params: TransformationParams = Field(default_factory=TransformationParams)


class ColumnMapping(BaseModel):
    """Maps a source column to a target column with optional transformation."""
    source_col: str = Field(description="Name of the source column")
    target_col: str = Field(description="Name of the target column")
    action: Literal["direct", "transform", "skip"] = Field(
        default="direct",
        description="Action: direct copy, apply transformation, or skip"
    )
    transform_id: Optional[str] = Field(
        default=None,
        description="ID of the transformation to apply (if action is 'transform')"
    )


class EnrichmentParams(BaseModel):
    """Parameters for an enrichment step."""
    provider: Optional[str] = None
    cache_ttl: Optional[int] = None
    
    class Config:
        extra = "allow"


class Enrichment(BaseModel):
    """An enrichment step that calls external APIs."""
    id: str = Field(description="Unique identifier for this enrichment")
    trigger_col: str = Field(description="Column that triggers the enrichment")
    target_cols: List[str] = Field(description="Columns to be populated")
    api_service: str = Field(description="Name of the API service to use")
    strategy: Literal["cache_first_then_api", "api_only", "cache_only"] = Field(
        default="cache_first_then_api"
    )
    params: EnrichmentParams = Field(default_factory=EnrichmentParams)


class TransformationPlan(BaseModel):
    """
    The complete transformation plan generated by the Planner Agent.
    This is the "contract" between the AI Planner and the Execution Engine.
    """
    transformation_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique ID for this transformation plan"
    )
    confidence_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Agent's confidence in this plan (0.0-1.0)"
    )
    column_mappings: List[ColumnMapping] = Field(
        default_factory=list,
        description="List of column mappings from source to target"
    )
    transformations: List[Transformation] = Field(
        default_factory=list,
        description="List of transformation steps"
    )
    enrichments: List[Enrichment] = Field(
        default_factory=list,
        description="List of enrichment steps"
    )
    unmapped_source_cols: List[str] = Field(
        default_factory=list,
        description="Source columns that couldn't be mapped"
    )
    unmapped_target_cols: List[str] = Field(
        default_factory=list,
        description="Target columns that have no source match"
    )
    warnings: List[str] = Field(
        default_factory=list,
        description="Warnings from the planning process"
    )
    requires_user_input: bool = Field(
        default=False,
        description="Whether user input is required to proceed"
    )
    user_questions: List[str] = Field(
        default_factory=list,
        description="Questions for the user if input is required"
    )
    
    def get_transformation_by_id(self, transform_id: str) -> Optional[Transformation]:
        """Get a transformation by its ID."""
        for t in self.transformations:
            if t.id == transform_id:
                return t
        return None
