"""
Validation Report Schema.
Defines the output of the Validation Agent.
"""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class ValidationError(BaseModel):
    """A single validation error for a specific cell."""
    row_index: int = Field(description="0-indexed row number")
    column: str = Field(description="Column name where error occurred")
    issue: str = Field(description="Description of the issue")
    value: Optional[str] = Field(default=None, description="The problematic value")
    severity: Literal["error", "warning"] = Field(
        default="error",
        description="Severity: 'error' blocks output, 'warning' is informational"
    )
    suggested_fix: Optional[str] = Field(
        default=None,
        description="Suggested fix for the issue"
    )


class ColumnValidation(BaseModel):
    """Validation summary for a single column."""
    column_name: str
    valid_count: int = 0
    invalid_count: int = 0
    null_count: int = 0
    validation_rate: float = 0.0


class ValidationReport(BaseModel):
    """
    The complete validation report generated by the Validation Agent.
    """
    status: Literal["success", "partial_success", "failed"] = Field(
        description="Overall status of the validation"
    )
    total_rows: int = Field(description="Total number of rows processed")
    successful_rows: int = Field(default=0, description="Rows that passed all validations")
    failed_rows: int = Field(default=0, description="Rows with at least one error")
    warning_rows: int = Field(default=0, description="Rows with warnings only")
    
    errors: List[ValidationError] = Field(
        default_factory=list,
        description="List of all validation errors"
    )
    
    column_validations: List[ColumnValidation] = Field(
        default_factory=list,
        description="Per-column validation statistics"
    )
    
    quality_score: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Overall quality score (0-100%)"
    )
    
    summary: str = Field(
        default="",
        description="Human-readable summary of the validation"
    )
    
    def compute_quality_score(self) -> float:
        """Compute the quality score based on error rates."""
        if self.total_rows == 0:
            return 0.0
        self.quality_score = (self.successful_rows / self.total_rows) * 100
        return self.quality_score
    
    def compute_status(self) -> str:
        """Determine the status based on error counts."""
        if self.failed_rows == 0:
            self.status = "success"
        elif self.failed_rows < self.total_rows * 0.1:  # Less than 10% failed
            self.status = "partial_success"
        else:
            self.status = "failed"
        return self.status
